export default {
  quoter: [
    'devicon-javascript-plain',
    'devicon-html5-plain',
    'devicon-css3-plain',
    'devicon-react-original',
    'devicon-nodejs-plain',
    'devicon-express-original',
    'devicon-mocha-plain',
    'devicon-postgresql-plain',
  ],
  miMood: [
    'devicon-javascript-plain',
    'devicon-html5-plain',
    'devicon-css3-plain',
    'devicon-react-original',
    'devicon-nodejs-plain',
    'devicon-express-original',
    'devicon-mocha-plain',
    'devicon-postgresql-plain',
    'devicon-amazonwebservices-original',
  ],
  molly: [
    'devicon-javascript-plain',
    'devicon-html5-plain',
    'devicon-css3-plain',
    'devicon-react-original',
    'devicon-nodejs-plain',
    'devicon-express-original',
    'devicon-postgresql-plain',
  ],
}